src/TechTrader/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechTrader.Models;
using Microsoft.EntityFrameworkCore;

namespace TechTrader.Controllers
{
    public class SellerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public IActionResult Index()
        {
            var thisSeller = db.Sellers.Include(i => i.Posts).FirstOrDefault(i => i.UserName == User.Identity.Name);
            if (thisSeller != null)
            {
                return View(thisSeller);
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Seller seller)
        {
            seller.UserName = User.Identity.Name;
            db.Sellers.Add(seller);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TechTrader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css" type="text/css" />
    @*<script src="~/js/scripts.js"></script>*@
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <ul class="nav nav-tabs">
        <li class="logo">@Html.ActionLink("Tech Trader", "Index", "Home")</li>
        @if (User.Identity.IsAuthenticated)
        {
            <li role="presentation">@Html.ActionLink(User.Identity.Name, "Index", "Seller")</li>
            <li class="nav pull-right">
                @using (Html.BeginForm("LogOff", "Account"))
                {
                    <input type="submit" id="logout" value="Logout" class="btn logout" />
                }
            </li>
        }
        else
        {
            <li class="nav pull-right">@Html.ActionLink("Register", "Register", "Account")</li>
            <li class="nav pull-right">@Html.ActionLink("Login", "Login", "Account")</li>
        }
    </ul>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>